import type { ChangeOrder, Estimate, Opportunity } from "@reformapro/domain/entities";
import { OpportunityUseCases, EstimateUseCases, ChangeOrderUseCases, type PublicChangeOrder } from "../../application/use-cases/sales.use-cases.js";
import { toHttpError } from "./errorMiddleware.js";
import type { HttpRequest, HttpResponse } from "./authController.js";

const dateOrNull = (value: unknown) => value ? new Date(String(value)) : null;
const opportunityDTO = (o: Opportunity) => ({ ...o, fechaVisita: o.fechaVisita?.toISOString() ?? null, createdAt: o.createdAt.toISOString(), updatedAt: o.updatedAt.toISOString() });
const estimateDTO = (e: Estimate) => ({ ...e, createdAt: e.createdAt.toISOString(), updatedAt: e.updatedAt.toISOString() });
const changeOrderDTO = (c: ChangeOrder) => ({ ...c, aprobadoAt: c.aprobadoAt?.toISOString() ?? null, createdAt: c.createdAt.toISOString() });
const publicChangeOrderDTO = (c: PublicChangeOrder) => ({ ...c, aprobadoAt: c.aprobadoAt?.toISOString() ?? null, createdAt: c.createdAt.toISOString() });
const isPublicChangeOrder = (change: ChangeOrder | PublicChangeOrder): change is PublicChangeOrder => "propuesta" in change;

export function salesController(deps: { opportunities: OpportunityUseCases; estimates: EstimateUseCases; changes: ChangeOrderUseCases }) {
  const ctx = (req: HttpRequest) => ({ ip: req.ip, userAgent: req.headers["user-agent"] ?? "unknown" });
  return {
    async editChange(req: HttpRequest & { actorId: number; params: { projectId: string; id: string } }): Promise<HttpResponse> { try { return { status: 200, body: changeOrderDTO(await deps.changes.edit(req.actorId, Number(req.params.projectId), Number(req.params.id), (req.body as { borrador: import("@reformapro/domain/entities").EstimateDraft }).borrador)) }; } catch (e) { return toHttpError(e); } },
    async transitionChange(req: HttpRequest & { actorId: number; params: { projectId: string; id: string } }): Promise<HttpResponse> { try { const body = req.body as { estado: string; password?: string }; const saved = await deps.changes.transition(req.actorId, Number(req.params.projectId), Number(req.params.id), body.estado, body.password); return { status: 200, body: isPublicChangeOrder(saved) ? publicChangeOrderDTO(saved) : changeOrderDTO(saved) }; } catch (e) { return toHttpError(e); } },
    async convertSolicitud(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { return { status: 200, body: opportunityDTO(await deps.opportunities.fromSolicitud(req.actorId, Number(req.params.id), (req.body as { direccion: string }).direccion)) }; } catch (e) { return toHttpError(e); } },
    async history(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { return { status: 200, body: await deps.estimates.history(req.actorId, Number(req.params.id)) }; } catch (e) { return toHttpError(e); } },
    async draft(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { return { status: 200, body: estimateDTO(await deps.estimates.adminDraft(req.actorId, Number(req.params.id))) }; } catch (e) { return toHttpError(e); } },
    async listOpportunities(req: HttpRequest & { actorId: number; query: { estado?: string } }): Promise<HttpResponse> { try { return { status: 200, body: (await deps.opportunities.list(req.actorId, req.query.estado as never)).map(opportunityDTO) }; } catch (e) { return toHttpError(e); } },
    async createOpportunity(req: HttpRequest & { actorId: number }): Promise<HttpResponse> { try { const body = (req.body ?? {}) as Record<string, unknown>; const saved = await deps.opportunities.create(req.actorId, { ...body, clienteId: body.clienteId == null ? null : Number(body.clienteId), fechaVisita: dateOrNull(body.fechaVisita) } as never, ctx(req)); return { status: 201, body: opportunityDTO(saved) }; } catch (e) { return toHttpError(e); } },
    async updateOpportunity(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { const body = (req.body ?? {}) as Record<string, unknown>; const saved = await deps.opportunities.update(req.actorId, Number(req.params.id), { ...body, clienteId: body.clienteId === undefined ? undefined : body.clienteId == null ? null : Number(body.clienteId), fechaVisita: body.fechaVisita === undefined ? undefined : dateOrNull(body.fechaVisita) } as never); return { status: 200, body: opportunityDTO(saved) }; } catch (e) { return toHttpError(e); } },
    async listEstimates(req: HttpRequest & { actorId: number; query?: Record<string,string> }): Promise<HttpResponse> { try { return { status: 200, body: await deps.estimates.publicList(req.actorId, { page: Number(req.query?.page ?? 0), search: req.query?.search ?? "", status: req.query?.status ?? "" }) }; } catch (e) { return toHttpError(e); } },
    async getEstimate(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { return { status: 200, body: await deps.estimates.publicGet(req.actorId, Number(req.params.id)) }; } catch (e) { return toHttpError(e); } },
    async createEstimate(req: HttpRequest & { actorId: number }): Promise<HttpResponse> { try { const body = (req.body ?? {}) as { oportunidadId: number; borrador: unknown }; return { status: 201, body: estimateDTO(await deps.estimates.create(req.actorId, Number(body.oportunidadId), body.borrador as never, ctx(req))) }; } catch (e) { return toHttpError(e); } },
    async updateEstimate(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { const body = (req.body ?? {}) as { borrador: unknown }; return { status: 200, body: estimateDTO(await deps.estimates.update(req.actorId, Number(req.params.id), body.borrador as never)) }; } catch (e) { return toHttpError(e); } },
    async sendEstimate(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { return { status: 200, body: estimateDTO(await deps.estimates.send(req.actorId, Number(req.params.id), ctx(req))) }; } catch (e) { return toHttpError(e); } },
    async signEstimate(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { const result = await deps.estimates.sign(req.actorId, Number(req.params.id), req.body as never, ctx(req)); return { status: 200, body: { estimate: await deps.estimates.publicGet(req.actorId, result.estimate.id), hash: result.hash, fechaFirma: result.fechaFirma.toISOString() } }; } catch (e) { return toHttpError(e); } },
    async rejectEstimate(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { const body = req.body as { motivo?: string }; const estimate = await deps.estimates.reject(req.actorId, Number(req.params.id), body.motivo ?? "", ctx(req)); return { status: 200, body: await deps.estimates.publicGet(req.actorId, estimate.id) }; } catch (e) { return toHttpError(e); } },
    async reviseEstimate(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { return { status: 200, body: estimateDTO(await deps.estimates.createRevision(req.actorId, Number(req.params.id))) }; } catch (e) { return toHttpError(e); } },
    async acceptEstimate(req: HttpRequest & { actorId: number; params: { id: string } }): Promise<HttpResponse> { try { const project = await deps.estimates.accept(req.actorId, Number(req.params.id), ctx(req)); return { status: 201, body: { id: project.id, estimateId: project.estimateId } }; } catch (e) { return toHttpError(e); } },
    async listChanges(req: HttpRequest & { actorId: number; params: { projectId: string } }): Promise<HttpResponse> { try { return { status: 200, body: (await deps.changes.list(req.actorId, Number(req.params.projectId))).map(change => isPublicChangeOrder(change) ? publicChangeOrderDTO(change) : changeOrderDTO(change)) }; } catch (e) { return toHttpError(e); } },
    async createChange(req: HttpRequest & { actorId: number; params: { projectId: string } }): Promise<HttpResponse> { try { return { status: 201, body: changeOrderDTO(await deps.changes.create(req.actorId, Number(req.params.projectId), (req.body as { borrador: unknown }).borrador as never)) }; } catch (e) { return toHttpError(e); } },
  };
}
