import { useMemo, useState } from "react";
import { Button } from "@/shared/ui";
import { formatMoney } from "@/shared/lib/formatters";
import { SalesApi, type CatalogItemDTO } from "@/features/sales/api/sales.api";
import { catalogCategories, filterCatalogItems, groupCatalogItems, validateCatalogForm } from "./catalog-manager.utils";

import { useCatalog } from "./useCatalog";
import { CatalogLoadState } from "./CatalogLoadState";

type Form = { reference: string; category: string; description: string; unit: string; salePrice: string; vatRate: string };
const blank = (): Form => ({ reference: "", category: "", description: "", unit: "ud", salePrice: "", vatRate: "21" });

export function CatalogManager({ api }: { api: SalesApi }) {
  const { items, loading, error: loadError, reload: load } = useCatalog(api, true); const [form, setForm] = useState<Form>(blank); const [editing, setEditing] = useState<number | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [includeArchived, setIncludeArchived] = useState(false);
  const categories = useMemo(() => catalogCategories(items), [items]);
  const displayedItems = useMemo(() => filterCatalogItems(items, { search, category, includeArchived }), [items, search, category, includeArchived]);
  const groups = useMemo(() => groupCatalogItems(displayedItems), [displayedItems]);
  const set = (field: keyof Form, value: string) => setForm(current => ({ ...current, [field]: value }));
  const submit = async () => {
    const validation = validateCatalogForm(form);
    if (Object.keys(validation).length) { setError(Object.values(validation)[0] ?? "Revisa los campos obligatorios"); return; }
    const payload = { reference: form.reference, category: form.category, description: form.description, unit: form.unit, salePrice: Number(form.salePrice), vatRate: Number(form.vatRate) };
    try { setSaving(true); setError(""); if (editing == null) await api.createCatalogItem(payload); else await api.updateCatalogItem(editing, payload); setForm(blank()); setEditing(null); await load(); } catch (cause) { setError((cause as { message?: string }).message ?? "No se pudo guardar la partida"); } finally { setSaving(false); }
  };
  const edit = (item: CatalogItemDTO) => { setEditing(item.id); setForm({ reference: item.reference, category: item.category, description: item.description, unit: item.unit, salePrice: String(item.salePrice), vatRate: String(item.vatRate) }); requestAnimationFrame(() => { const input = document.querySelector<HTMLInputElement>(".catalog-manager .sales-card input"); input?.scrollIntoView({ behavior: "smooth", block: "center" }); input?.focus(); }); };
  const archive = async (item: CatalogItemDTO) => { if (!item.active || !window.confirm(`¿Archivar ${item.reference}? Dejará de aparecer al crear propuestas.`)) return; try { await api.archiveCatalogItem(item.id); await load(); } catch (cause) { setError((cause as { message?: string }).message ?? "No se pudo archivar la partida"); } };
  return <section className="private-page catalog-manager"><header className="private-page-header"><div className="private-page-header__copy"><p className="eyebrow">Administración</p><h1>Catálogo de partidas</h1><p>Solo administradores. Archivar conserva el histórico de propuestas.</p></div><div className="private-page-header__actions"><Button small variant="ghost" disabled={loading || saving} onClick={() => void load()}>Actualizar</Button></div></header>
    <section className="sales-card"><h2>{editing == null ? "Nueva partida" : "Editar partida"}</h2>{error && <p role="alert" style={{ color: "#a43c32" }}>{error}</p>}<div className="estimate-line__main"><label>Referencia *<input value={form.reference} onChange={e => set("reference", e.target.value)} placeholder="DEM-007" /></label><label>Categoría *<input list="catalog-categories" value={form.category} onChange={e => set("category", e.target.value)} placeholder="Demoliciones" /><datalist id="catalog-categories">{categories.map(value => <option key={value} value={value} />)}</datalist></label><label>Descripción *<input value={form.description} onChange={e => set("description", e.target.value)} /></label><label>Unidad *<input value={form.unit} onChange={e => set("unit", e.target.value)} /></label><label>Precio sin IVA *<input type="number" min="0" step="0.01" value={form.salePrice} onChange={e => set("salePrice", e.target.value)} /></label><label>IVA (%) *<input type="number" min="0" max="100" value={form.vatRate} onChange={e => set("vatRate", e.target.value)} /></label></div><div style={{ display: "flex", gap: 8, marginTop: 16 }}><Button loading={saving} onClick={() => void submit()}>{editing == null ? "Crear partida" : "Guardar cambios"}</Button>{editing != null && <Button variant="ghost" onClick={() => { setEditing(null); setForm(blank()); }}>Cancelar</Button>}</div></section>
    <section className="sales-card sales-card--wide catalog-manager__registered"><div className="catalog-manager__heading"><div><h2>Partidas registradas</h2><p>Organizadas por capítulos para localizar y mantener cada partida con rapidez.</p></div>{!loading && !loadError && <span>{displayedItems.length} {displayedItems.length === 1 ? "partida" : "partidas"}</span>}</div><div className="catalog-manager__filters"><label>Buscar partida<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Referencia o descripción" /></label><label>Categoría<select value={category} onChange={event => setCategory(event.target.value)}><option value="">Todas las categorías</option>{categories.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label className="catalog-manager__archived"><input type="checkbox" checked={includeArchived} onChange={event => setIncludeArchived(event.target.checked)} /> Incluir archivadas</label>{(search || category || includeArchived) && <Button small variant="ghost" onClick={() => { setSearch(""); setCategory(""); setIncludeArchived(false); }}>Limpiar filtros</Button>}</div>{loading || loadError ? <CatalogLoadState loading={loading} error={loadError} reload={load} /> : groups.length === 0 ? <p className="catalog-manager__empty">{items.length === 0 ? "Todavía no hay partidas guardadas en el catálogo." : !search && !category && !includeArchived && items.every(item => !item.active) ? "Todas las partidas están archivadas. Activa «Incluir archivadas» para consultarlas." : "No hay partidas que coincidan con estos filtros."}</p> : <div className="catalog-manager__groups">{groups.map(group => <section className="catalog-manager__group" key={group.category}><header><div><p className="eyebrow">Capítulo</p><h3>{group.category}</h3></div><span>{group.items.length} {group.items.length === 1 ? "partida" : "partidas"}</span></header><div className="private-table-scroll catalog-manager__table-scroll"><table className="catalog-manager__table"><thead><tr><th>Ref.</th><th>Partida</th><th>Precio</th><th>Estado</th><th /></tr></thead><tbody>{group.items.map(item => <tr key={item.id} style={{ opacity: item.active ? 1 : .55 }}><td data-label="Referencia"><code>{item.reference}</code></td><td data-label="Partida"><strong>{item.description}</strong><br/><small>{item.unit} · IVA {item.vatRate}%</small></td><td data-label="Precio">{formatMoney(item.salePrice)}</td><td data-label="Estado">{item.active ? "Activa" : "Archivada"}</td><td><div style={{ display: "flex", gap: 8 }}><Button small variant="ghost" onClick={() => edit(item)}>Editar</Button>{item.active && <Button small variant="ghost" onClick={() => void archive(item)}>Archivar</Button>}</div></td></tr>)}</tbody></table></div></section>)}</div>}</section>
  </section>;
}
