import { describe, expect, it } from "vitest";
import { activationTokenFromLocation } from "./activation-token";

describe("activationTokenFromLocation", () => {
  it("reads the token from the hash-router query generated by invitations", () => {
    expect(
      activationTokenFromLocation({
        search: "",
        hash: "#/activar-cuenta?token=one%20time",
      }),
    ).toBe("one time");
  });

  it("keeps compatibility with a regular query and rejects unrelated hashes", () => {
    expect(activationTokenFromLocation({ search: "?token=legacy", hash: "" })).toBe("legacy");
    expect(activationTokenFromLocation({ search: "", hash: "#/login?token=foreign" })).toBe("");
  });
});
