import type { AuditEntry, CatalogItem, ChangeOrder, Estimate, EstimateVersion, Opportunity, OpportunityStatus, Project, User, UserRole } from "../entities/index.js";

export interface IUserRepository { findById(id: number): Promise<User | null>; findByEmail(email: string): Promise<User | null>; findAll(): Promise<User[]>; findByRole(role: UserRole): Promise<User[]>; save(user: User, passwordHash?: string): Promise<User>; update(id: number, changes: Partial<Omit<User, "id" | "createdAt">>, passwordHash?: string): Promise<User>; delete(id: number): Promise<void>; verifyPassword(email: string, plaintext: string): Promise<User | null>; updatePassword(id: number, hash: string): Promise<void>; revokeSessions(id: number): Promise<void>; }
export interface IProjectRepository { findById(id: number): Promise<Project | null>; findByClient(id: number): Promise<Project[]>; findByProfesional(id: number): Promise<Project[]>; findAll(): Promise<Project[]>; save(project: Project): Promise<Project>; update(id: number, changes: Partial<Omit<Project, "id" | "createdAt">>, expectedRevision?: number): Promise<Project>; }
export interface IOpportunityRepository { findById(id: number): Promise<Opportunity | null>; findAll(status?: OpportunityStatus): Promise<Opportunity[]>; save(opportunity: Omit<Opportunity, "id" | "createdAt" | "updatedAt">): Promise<Opportunity>; fromSolicitud(id: number, opportunity: Omit<Opportunity, "id" | "createdAt" | "updatedAt">): Promise<Opportunity>; update(id: number, changes: Partial<Omit<Opportunity, "id" | "createdAt" | "updatedAt">>): Promise<Opportunity>; }
export interface IEstimateRepository { findById(id: number): Promise<Estimate | null>; findAll(): Promise<Estimate[]>; findPage(query: EstimatePageQuery): Promise<Estimate[]>; save(estimate: Omit<Estimate, "id" | "createdAt" | "updatedAt">): Promise<Estimate>; update(id: number, changes: Partial<Pick<Estimate, "titulo" | "estado" | "versionActual" | "borrador" | "motivoRechazo">>): Promise<Estimate>; saveVersion(version: Omit<EstimateVersion, "id" | "createdAt">): Promise<EstimateVersion>; findVersions(estimateId: number): Promise<EstimateVersion[]>; signVersion(estimateId: number, version: number, firma: Record<string, unknown>, firmadoAt: Date): Promise<EstimateVersion>; }
export interface IChangeOrderRepository { findByProject(projectId: number): Promise<ChangeOrder[]>; save(change: Omit<ChangeOrder, "id" | "createdAt">): Promise<ChangeOrder>; update(id: number, changes: Partial<Pick<ChangeOrder, "estado" | "payload" | "aprobadoAt">>): Promise<ChangeOrder>; transition(id: number, projectId: number, expected: ChangeOrder["estado"], next: ChangeOrder["estado"], actorId: number): Promise<ChangeOrder>; }
export interface ICatalogRepository {
  findAll(includeInactive?: boolean): Promise<CatalogItem[]>;
  findById(id: number): Promise<CatalogItem | null>;
  findByReference(reference: string): Promise<CatalogItem | null>;
  save(item: Omit<CatalogItem, "id" | "createdAt" | "updatedAt">): Promise<CatalogItem>;
  update(id: number, changes: Partial<Pick<CatalogItem, "reference" | "category" | "description" | "unit" | "salePrice" | "vatRate" | "active">>): Promise<CatalogItem>;
}
export interface EstimatePageQuery { clientId?: number; page: number; limit: number; search: string; status: string; }
export interface IAuditRepository { append(entry: AuditEntry): Promise<void>; findAll(opts: { page?: number; limit?: number; action?: string | null; userId?: number | null; from?: Date | null; to?: Date | null }): Promise<{ items: AuditEntry[]; total: number; page: number; limit: number; pages: number }>; }
