import type { AuditEntry, Budget, ChangeOrder, Estimate, EstimateDraft, EstimateVersion, Opportunity, OpportunityStatus, Project, User, UserRole } from "../entities/index.js";
export interface IUserRepository { findById(id: number): Promise<User | null>; findByEmail(email: string): Promise<User | null>; findAll(): Promise<User[]>; findByRole(role: UserRole): Promise<User[]>; save(user: User, passwordHash?: string): Promise<User>; update(id: number, changes: Partial<Omit<User, "id" | "createdAt">>): Promise<User>; delete(id: number): Promise<void>; verifyPassword(email: string, plaintext: string): Promise<User | null>; updatePassword(id: number, hash: string): Promise<void>; }
export interface IProjectRepository { findById(id: number): Promise<Project | null>; findByClient(id: number): Promise<Project[]>; findByProfesional(id: number): Promise<Project[]>; findAll(): Promise<Project[]>; save(project: Project): Promise<Project>; update(id: number, changes: Partial<Omit<Project, "id" | "createdAt">>): Promise<Project>; delete(id: number): Promise<void>; }
export interface IBudgetRepository { findById(id: number): Promise<Budget | null>; findByProject(id: number): Promise<Budget[]>; findByClient(id: number): Promise<Budget[]>; findAll(): Promise<Budget[]>; save(budget: Budget): Promise<Budget>; update(id: number, changes: Partial<Budget>): Promise<Budget>; delete(id: number): Promise<void>; }
export interface IOpportunityRepository { findById(id: number): Promise<Opportunity | null>; findAll(status?: OpportunityStatus): Promise<Opportunity[]>; save(opportunity: Omit<Opportunity, "id" | "createdAt" | "updatedAt">): Promise<Opportunity>; update(id: number, changes: Partial<Omit<Opportunity, "id" | "createdAt" | "updatedAt">>): Promise<Opportunity>; }
export interface IEstimateRepository { findById(id: number): Promise<Estimate | null>; findAll(): Promise<Estimate[]>; findByOpportunity(opportunityId: number): Promise<Estimate[]>; save(estimate: Omit<Estimate, "id" | "createdAt" | "updatedAt">): Promise<Estimate>; update(id: number, changes: Partial<Pick<Estimate, "titulo" | "estado" | "versionActual" | "borrador" | "motivoRechazo">>): Promise<Estimate>; saveVersion(version: Omit<EstimateVersion, "id" | "createdAt">): Promise<EstimateVersion>; findVersions(estimateId: number): Promise<EstimateVersion[]>; signVersion(estimateId: number, version: number, firma: Record<string, unknown>, firmadoAt: Date): Promise<EstimateVersion>; }
export interface IChangeOrderRepository { findByProject(projectId: number): Promise<ChangeOrder[]>; save(change: Omit<ChangeOrder, "id" | "createdAt">): Promise<ChangeOrder>; update(id: number, changes: Partial<Pick<ChangeOrder, "estado" | "payload" | "aprobadoAt">>): Promise<ChangeOrder>; }
export interface Challenge { challenge: string; timestamp: number; exp: number; userId: number; }
export interface IChallengeRepository { get(id: number): Promise<Challenge | null>; set(id: number, challenge: Challenge): Promise<void>; delete(id: number): Promise<void>; }
export interface IAuditRepository { append(entry: AuditEntry): Promise<void>; findAll(opts: { page?: number; limit?: number; action?: string | null; userId?: number | null; from?: Date | null; to?: Date | null }): Promise<{ items: AuditEntry[]; total: number; page: number; limit: number; pages: number }>; }
