import { useEffect, useRef, useState } from "react";
import { Button, Input, Modal } from "@/shared/ui";
import { SignatureCanvas, type SignatureCanvasHandle } from "@/features/signatures/components/SignatureCanvas";
import type { ProjectsApi, ProjectDTO } from "@/features/projects/api/projects.api";
import { formatMoney } from "@/shared/lib/formatters";
import { SalesApi, type EstimateDTO } from "../api/sales.api";

const consent = "Acepto la propuesta mostrada y autorizo el inicio de los trabajos descritos en sus condiciones.";
export function ClientEstimates({ api, projectsApi }: { api: SalesApi; projectsApi: ProjectsApi }) {
  const [items, setItems] = useState<EstimateDTO[]>([]); const [projects, setProjects] = useState<ProjectDTO[]>([]); const [error, setError] = useState(""); const [selected, setSelected] = useState<EstimateDTO | null>(null); const [signature, setSignature] = useState(""); const [password, setPassword] = useState(""); const [accepted, setAccepted] = useState(false); const [saving, setSaving] = useState(false); const [receipt, setReceipt] = useState<{ hash: string; date: string } | null>(null); const canvas = useRef<SignatureCanvasHandle>(null);
  const refresh = () => Promise.all([api.estimates(), projectsApi.list()]).then(([estimates, ownProjects]) => { setItems(estimates); setProjects(ownProjects); }).catch(e => setError(e.message ?? "No se pudo cargar tu área"));
  useEffect(() => { void refresh(); }, []);
  const close = () => { setSelected(null); setSignature(""); setPassword(""); setAccepted(false); canvas.current?.clear(); };
  const sign = async () => { if (!selected || !signature || !password || !accepted) return; try { setSaving(true); const result = await api.signEstimate(selected.id, { password, canvasSignature: signature, consentimiento: consent }); setItems(items.map(item => item.id === result.estimate.id ? result.estimate : item)); close(); setReceipt({ hash: result.hash, date: result.fechaFirma }); } catch (e) { setError((e as { message?: string }).message ?? "No se pudo firmar la propuesta"); } finally { setSaving(false); } };
  const reject = async () => { if (!selected) return; const motivo = window.prompt("Indica qué deseas revisar o por qué no aceptas la propuesta:"); if (!motivo?.trim()) return; try { setSaving(true); const updated = await api.rejectEstimate(selected.id, motivo); setItems(items.map(item => item.id === updated.id ? updated : item)); close(); } catch (e) { setError((e as { message?: string }).message ?? "No se pudo enviar la solicitud"); } finally { setSaving(false); } };
  return <section><header className="private-page-header" style={{ marginBottom: 24 }}><p className="eyebrow">Área cliente</p><h1>Tu proyecto con Hogaria</h1><p style={{ color:"#71685e" }}>Consulta tus propuestas, firma solo cuando hayas revisado cada detalle y sigue el avance de tu obra.</p></header>{error && <p role="alert" style={{ color:"#a43c32" }}>{error}</p>}
    <h2>Propuestas</h2>{items.length ? items.map(item => <article key={item.id} className="private-action-card" style={{ padding:"18px 0", borderBottom:"1px solid var(--line)", display:"flex", justifyContent:"space-between", gap:16, alignItems:"center" }}><div><strong>{item.titulo}</strong><p style={{ margin:"6px 0", color:"#71685e" }}>{item.numero} · versión {item.versionActual} · {item.estado}</p>{item.propuesta && <strong>{formatMoney(item.propuesta.totalConIva)}</strong>}</div><div style={{ display:"flex", gap:8, flexWrap:"wrap" }}><Button small variant="ghost" onClick={() => setSelected(item)}>Ver propuesta</Button>{item.estado === "enviado" && <Button small onClick={() => setSelected(item)}>Firmar</Button>}</div></article>) : <p>Aún no tienes propuestas disponibles.</p>}
    <h2 style={{ marginTop:36 }}>Mis proyectos</h2>{projects.length ? projects.map(project => <article key={project.id} style={{ padding:"18px 0", borderBottom:"1px solid var(--line)", display:"flex", justifyContent:"space-between", gap:16 }}><div><strong>{project.nombre}</strong><p style={{ margin:"6px 0", color:"#71685e" }}>{project.direccion} · {project.progreso}% completado</p></div><a className="ui-button ui-button--ghost" href={`#/cliente/projects/${project.id}`}>Ver obra</a></article>) : <p>Cuando una propuesta firmada se convierta en obra, aparecerá aquí.</p>}
    <Modal open={selected !== null} onClose={close} title={selected?.titulo ?? "Propuesta"} width={760}>{selected?.propuesta ? <><p style={{ color:"#71685e" }}>Versión {selected.versionActual} · enviada {selected.propuesta.enviadoAt ? new Date(selected.propuesta.enviadoAt).toLocaleDateString("es-ES") : "—"}</p><div className="private-table-scroll"><table><thead><tr><th>Partida</th><th>Cantidad</th><th>Precio</th><th>IVA</th></tr></thead><tbody>{selected.propuesta.partidas.map(line => <tr key={line.id}><td>{line.descripcion}</td><td>{line.cantidad} {line.unidad}</td><td>{formatMoney(line.precioVentaUnitario)}</td><td>{line.iva}%</td></tr>)}</tbody></table></div><p><strong>Total sin IVA:</strong> {formatMoney(selected.propuesta.totalSinIva)}<br/><strong>IVA:</strong> {formatMoney(selected.propuesta.totalIva)}<br/><strong>Total:</strong> {formatMoney(selected.propuesta.totalConIva)}</p><h3>Condiciones</h3><p style={{ whiteSpace:"pre-wrap" }}>{selected.propuesta.condicionesPago}</p>{selected.estado === "enviado" && <><h3>Firma</h3><p style={{ color:"#71685e" }}>Lee la propuesta completa antes de firmar. La firma dejará esta versión sellada.</p><SignatureCanvas ref={canvas} onChange={setSignature} height={150}/><label style={{ display:"flex", gap:8, margin:"16px 0", fontSize:13 }}><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{consent}</label><Input label="Contraseña" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></>}</> : <p>Esta propuesta aún no ha sido enviada.</p>}<footer style={{ display:"flex", justifyContent:"space-between", gap:8, marginTop:20 }}><Button variant="ghost" onClick={close}>Cerrar</Button>{selected?.estado === "enviado" && <div style={{ display:"flex", gap:8 }}><Button variant="ghost" loading={saving} onClick={() => void reject()}>Solicitar cambios</Button><Button disabled={!signature || !password || !accepted} loading={saving} onClick={() => void sign()}>Firmar y aceptar</Button></div>}</footer></Modal>
    <Modal open={receipt !== null} onClose={() => setReceipt(null)} title="Propuesta firmada" width={560}><h2>Firma registrada correctamente</h2><p>Tu aceptación ha quedado sellada. Conserva esta referencia; también estará disponible en tu propuesta.</p><p><strong>Fecha:</strong> {receipt ? new Date(receipt.date).toLocaleString("es-ES") : ""}</p><code style={{ display:"block", wordBreak:"break-all", padding:10, background:"#f8efe4" }}>{receipt?.hash}</code><footer style={{ marginTop:20 }}><Button onClick={() => setReceipt(null)}>Entendido</Button></footer></Modal>
  </section>;
}
