import { useEffect, useMemo, useState } from "react";
import { Button } from "@/shared/ui";
import type { UsersApi } from "@/features/users/api/users.api";
import { SalesApi, type EstimateDraftDTO, type EstimateDTO, type OpportunityDTO } from "../api/sales.api";

const newLine = () => ({ id: crypto.randomUUID(), categoria: "General", descripcion: "", cantidad: 1, unidad: "ud", precioVentaUnitario: 0, costeUnitario: null, descuento: 0, iva: 21 });
const blankDraft = (): EstimateDraftDTO => ({ titulo: "", validezDias: 30, condicionesPago: "", garantia: "", notasCliente: "", notasInternas: "", partidas: [newLine()] });
const steps = ["Oportunidad", "Alcance", "Partidas", "Revisión"];

export function SalesPipeline({ api, users }: { api: SalesApi; users: UsersApi }) {
  const [opportunities, setOpportunities] = useState<OpportunityDTO[]>([]); const [estimates, setEstimates] = useState<EstimateDTO[]>([]); const [clients, setClients] = useState<Array<{ id: number; nombre: string }>>([]);
  const [step, setStep] = useState(0); const [saving, setSaving] = useState(false); const [converting, setConverting] = useState<number | null>(null); const [error, setError] = useState("");
  const [opportunity, setOpportunity] = useState({ clienteId: "", nombre: "", direccion: "", tipo: "Reforma integral", descripcion: "" }); const [selected, setSelected] = useState<number | null>(null); const [draft, setDraft] = useState(blankDraft);
  const refresh = () => Promise.all([api.opportunities(), api.estimates(), users.list("cliente")]).then(([o, e, c]) => { setOpportunities(o); setEstimates(e); setClients(c.map(x => ({ id: x.id, nombre: x.nombre }))); });
  useEffect(() => { void refresh(); }, []);
  const active = useMemo(() => opportunities.find(o => o.id === selected) ?? null, [opportunities, selected]);
  const opportunityComplete = Boolean(opportunity.clienteId && opportunity.nombre.trim() && opportunity.direccion.trim() && opportunity.tipo.trim());
  const scopeComplete = Boolean(active && draft.titulo.trim() && Number.isInteger(draft.validezDias) && draft.validezDias >= 1 && draft.validezDias <= 365 && draft.condicionesPago.trim());
  const linesComplete = draft.partidas.length > 0 && draft.partidas.every(line => line.descripcion.trim() && Number.isFinite(line.cantidad) && line.cantidad > 0 && Number.isFinite(line.precioVentaUnitario) && line.precioVentaUnitario >= 0 && Number.isFinite(line.iva) && line.iva >= 0);
  const submitOpportunity = async () => { if (!opportunityComplete) return; setError(""); try { setSaving(true); const saved = await api.createOpportunity({ clienteId: Number(opportunity.clienteId), nombre: opportunity.nombre.trim(), email: null, telefono: null, direccion: opportunity.direccion.trim(), tipo: opportunity.tipo.trim(), descripcion: opportunity.descripcion.trim(), estado: "nueva", fechaVisita: null, notasInternas: "" }); setSelected(saved.id); setStep(1); await refresh(); } catch (e) { setError((e as { message?: string }).message ?? "No se pudo guardar la oportunidad"); } finally { setSaving(false); } };
  const submitEstimate = async () => { if (!selected || !scopeComplete || !linesComplete) return; setError(""); try { setSaving(true); await api.createEstimate(selected, draft); setStep(0); setSelected(null); setDraft(blankDraft()); await refresh(); } catch (e) { setError((e as { message?: string }).message ?? "No se pudo crear la propuesta"); } finally { setSaving(false); } };
  const convert = async (estimate: EstimateDTO) => { try { setConverting(estimate.id); const project = await api.convertToProject(estimate.id); await refresh(); window.location.hash = `#/admin/projects/${project.id}`; } catch (e) { setError((e as { message?: string }).message ?? "No se pudo crear el proyecto"); } finally { setConverting(null); } };
  const updateLine = (index: number, changes: Partial<EstimateDraftDTO["partidas"][number]>) => setDraft({ ...draft, partidas: draft.partidas.map((line, i) => i === index ? { ...line, ...changes } : line) });
  return <section><header style={{ display: "flex", justifyContent: "space-between", alignItems: "end", gap: 16, marginBottom: 24 }}><div><p className="eyebrow">Ventas y propuestas</p><h1 style={{ margin: 0 }}>De oportunidad a obra</h1><p style={{ color: "#71685e" }}>Una propuesta se crea antes del proyecto y conserva cada versión enviada.</p></div><Button small variant="ghost" onClick={() => void refresh()}>Actualizar</Button></header>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 8, marginBottom: 24 }}>{steps.map((label, index) => <button key={label} onClick={() => index <= step && setStep(index)} style={{ padding: "11px 8px", border: "1px solid var(--line)", background: index === step ? "#c17248" : "#fffaf4", color: index === step ? "white" : "#51493f", borderRadius: 6, fontWeight: 700, cursor: index <= step ? "pointer" : "default" }}>{index + 1}. {label}</button>)}</div>
    {error && <p role="alert" style={{ color: "#a43c32" }}>{error}</p>}
    {step === 0 && <div className="sales-card"><h2>Nueva oportunidad</h2><p>Los campos con * son obligatorios.</p><label>Cliente existente *<select required value={opportunity.clienteId} onChange={e => setOpportunity({ ...opportunity, clienteId: e.target.value })}><option value="">Selecciona un cliente</option>{clients.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Nombre de la oportunidad *<input required value={opportunity.nombre} onChange={e => setOpportunity({ ...opportunity, nombre: e.target.value })} placeholder="Reforma vivienda García" /></label><label>Dirección *<input required value={opportunity.direccion} onChange={e => setOpportunity({ ...opportunity, direccion: e.target.value })} /></label><label>Tipo *<input required value={opportunity.tipo} onChange={e => setOpportunity({ ...opportunity, tipo: e.target.value })} /></label><label>Necesidad del cliente<textarea value={opportunity.descripcion} onChange={e => setOpportunity({ ...opportunity, descripcion: e.target.value })} /></label><Button disabled={!opportunityComplete} onClick={() => void submitOpportunity()} loading={saving}>Continuar</Button></div>}
    {step === 1 && <div className="sales-card"><h2>Alcance de la propuesta</h2><p>{active ? `${active.nombre} · ${active.direccion}` : "Selecciona una oportunidad"}</p><label>Título visible al cliente *<input required value={draft.titulo} onChange={e => setDraft({ ...draft, titulo: e.target.value })} placeholder="Reforma integral de vivienda" /></label><label>Validez (días) *<input required min="1" max="365" type="number" value={draft.validezDias} onChange={e => setDraft({ ...draft, validezDias: Number(e.target.value) })} /></label><label>Condiciones de pago *<textarea required value={draft.condicionesPago} onChange={e => setDraft({ ...draft, condicionesPago: e.target.value })} /></label><Button disabled={!scopeComplete} onClick={() => setStep(2)}>Continuar</Button></div>}
    {step === 2 && <div className="sales-card"><h2>Partidas y control interno</h2><p>Descripción, cantidad y precio de venta son obligatorios.</p>{draft.partidas.map((line, index) => <div key={line.id} style={{ display: "grid", gridTemplateColumns: "2fr 80px 100px 100px", gap: 8, marginBottom: 8 }}><input required value={line.descripcion} placeholder="Descripción *" onChange={e => updateLine(index, { descripcion: e.target.value })} /><input required min="0.01" type="number" value={line.cantidad} onChange={e => updateLine(index, { cantidad: Number(e.target.value) })} /><input required min="0" type="number" value={line.precioVentaUnitario} onChange={e => updateLine(index, { precioVentaUnitario: Number(e.target.value) })} /><input min="0" type="number" placeholder="Coste interno" value={line.costeUnitario ?? ""} onChange={e => updateLine(index, { costeUnitario: e.target.value === "" ? null : Number(e.target.value) })} /></div>)}<Button small variant="ghost" onClick={() => setDraft({ ...draft, partidas: [...draft.partidas, newLine()] })}>Añadir partida</Button><div style={{ marginTop: 16 }}><Button disabled={!linesComplete} onClick={() => setStep(3)}>Revisar propuesta</Button></div></div>}
    {step === 3 && <div className="sales-card"><h2>Revisión antes de guardar</h2><p><strong>{draft.titulo}</strong> · {draft.partidas.length} partidas · cliente: {active?.nombre}</p><p>Las notas y costes internos no forman parte de la versión que verá el cliente.</p><Button disabled={!scopeComplete || !linesComplete} onClick={() => void submitEstimate()} loading={saving}>Guardar como borrador</Button></div>}
    <div style={{ marginTop: 32 }}><h2>Propuestas recientes</h2>{estimates.length ? estimates.map(e => <div key={e.id} style={{ padding: "12px 0", borderBottom: "1px solid var(--line)", display: "flex", justifyContent: "space-between", alignItems:"center", gap:12 }}><span><strong>{e.numero}</strong> · {e.titulo} · v{e.versionActual} · {e.estado}</span>{e.estado === "firmado" && <Button small loading={converting === e.id} onClick={() => void convert(e)}>Crear proyecto</Button>}</div>) : <p>Aún no hay propuestas.</p>}</div>
  </section>;
}
