import { useEffect, useMemo, useState } from "react";
import { Button } from "@/shared/ui";
import type { UsersApi } from "@/features/users/api/users.api";
import { SalesApi, type EstimateDraftDTO, type EstimateDTO, type OpportunityDTO } from "../api/sales.api";

const newLine = () => ({ id: crypto.randomUUID(), categoria: "General", descripcion: "", cantidad: 1, unidad: "ud", precioVentaUnitario: 0, costeUnitario: null, descuento: 0, iva: 21 });
const blankDraft = (): EstimateDraftDTO => ({ titulo: "", validezDias: 30, condicionesPago: "", garantia: "", notasCliente: "", notasInternas: "", partidas: [newLine()] });
const steps = ["Oportunidad", "Alcance", "Partidas", "Revisión"];

export function SalesPipeline({ api, users }: { api: SalesApi; users: UsersApi }) {
  const [opportunities, setOpportunities] = useState<OpportunityDTO[]>([]); const [estimates, setEstimates] = useState<EstimateDTO[]>([]); const [clients, setClients] = useState<Array<{ id:number; nombre:string }>>([]);
  const [step, setStep] = useState(0); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [opportunity, setOpportunity] = useState({ clienteId: "", nombre: "", direccion: "", tipo: "Reforma integral", descripcion: "" }); const [selected, setSelected] = useState<number | null>(null); const [draft, setDraft] = useState(blankDraft);
  const refresh = () => Promise.all([api.opportunities(), api.estimates(), users.list("cliente")]).then(([o,e,c]) => { setOpportunities(o); setEstimates(e); setClients(c.map(x => ({ id:x.id, nombre:x.nombre }))); });
  useEffect(() => { void refresh(); }, []);
  const active = useMemo(() => opportunities.find(o => o.id === selected) ?? null, [opportunities, selected]);
  const submitOpportunity = async () => { setError(""); try { setSaving(true); const saved = await api.createOpportunity({ clienteId: Number(opportunity.clienteId) || null, nombre: opportunity.nombre, email: null, telefono: null, direccion: opportunity.direccion, tipo: opportunity.tipo, descripcion: opportunity.descripcion, estado: "nueva", fechaVisita: null, notasInternas: "" }); setSelected(saved.id); setStep(1); await refresh(); } catch (e) { setError((e as {message?:string}).message ?? "No se pudo guardar la oportunidad"); } finally { setSaving(false); } };
  const submitEstimate = async () => { if (!selected) return; setError(""); try { setSaving(true); await api.createEstimate(selected, draft); setStep(0); setSelected(null); setDraft(blankDraft()); await refresh(); } catch (e) { setError((e as {message?:string}).message ?? "No se pudo crear la propuesta"); } finally { setSaving(false); } };
  return <section><header style={{ display:"flex", justifyContent:"space-between", alignItems:"end", gap:16, marginBottom:24 }}><div><p className="eyebrow">Ventas y propuestas</p><h1 style={{ margin:0 }}>De oportunidad a obra</h1><p style={{ color:"#71685e" }}>Una propuesta se crea antes del proyecto y conserva cada versión enviada.</p></div><Button small variant="ghost" onClick={() => void refresh()}>Actualizar</Button></header>
    <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:8, marginBottom:24 }}>{steps.map((label,index) => <button key={label} onClick={() => index <= step && setStep(index)} style={{ padding:"11px 8px", border:"1px solid var(--line)", background:index === step ? "#c17248" : "#fffaf4", color:index === step ? "white" : "#51493f", borderRadius:6, fontWeight:700, cursor:index <= step ? "pointer" : "default" }}>{index + 1}. {label}</button>)}</div>
    {error && <p role="alert" style={{ color:"#a43c32" }}>{error}</p>}
    {step === 0 && <div className="sales-card"><h2>Nueva oportunidad</h2><p>Registra el contacto y el espacio. El proyecto todavía no existe.</p><label>Cliente existente<select value={opportunity.clienteId} onChange={e => setOpportunity({...opportunity,clienteId:e.target.value})}><option value="">Selecciona un cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Nombre de la oportunidad<input value={opportunity.nombre} onChange={e=>setOpportunity({...opportunity,nombre:e.target.value})} placeholder="Reforma vivienda García" /></label><label>Dirección<input value={opportunity.direccion} onChange={e=>setOpportunity({...opportunity,direccion:e.target.value})} /></label><label>Tipo<input value={opportunity.tipo} onChange={e=>setOpportunity({...opportunity,tipo:e.target.value})} /></label><label>Necesidad del cliente<textarea value={opportunity.descripcion} onChange={e=>setOpportunity({...opportunity,descripcion:e.target.value})} /></label><Button onClick={() => void submitOpportunity()} loading={saving}>Continuar</Button></div>}
    {step === 1 && <div className="sales-card"><h2>Alcance de la propuesta</h2><p>{active ? `${active.nombre} · ${active.direccion}` : "Selecciona una oportunidad"}</p><label>Título visible al cliente<input value={draft.titulo} onChange={e=>setDraft({...draft,titulo:e.target.value})} placeholder="Reforma integral de vivienda" /></label><label>Validez (días)<input type="number" value={draft.validezDias} onChange={e=>setDraft({...draft,validezDias:Number(e.target.value)})} /></label><label>Condiciones de pago<textarea value={draft.condicionesPago} onChange={e=>setDraft({...draft,condicionesPago:e.target.value})} /></label><Button onClick={() => setStep(2)}>Continuar</Button></div>}
    {step === 2 && <div className="sales-card"><h2>Partidas y control interno</h2>{draft.partidas.map((line,index)=><div key={line.id} style={{ display:"grid", gridTemplateColumns:"2fr 80px 100px 100px", gap:8, marginBottom:8 }}><input value={line.descripcion} placeholder="Descripción" onChange={e=>setDraft({...draft,partidas:draft.partidas.map((p,i)=>i===index?{...p,descripcion:e.target.value}:p)})}/><input type="number" value={line.cantidad} onChange={e=>setDraft({...draft,partidas:draft.partidas.map((p,i)=>i===index?{...p,cantidad:Number(e.target.value)}:p)})}/><input type="number" value={line.precioVentaUnitario} onChange={e=>setDraft({...draft,partidas:draft.partidas.map((p,i)=>i===index?{...p,precioVentaUnitario:Number(e.target.value)}:p)})}/><input type="number" placeholder="Coste interno" value={line.costeUnitario ?? ""} onChange={e=>setDraft({...draft,partidas:draft.partidas.map((p,i)=>i===index?{...p,costeUnitario:e.target.value===""?null:Number(e.target.value)}:p)})}/></div>)}<Button small variant="ghost" onClick={()=>setDraft({...draft,partidas:[...draft.partidas,newLine()]})}>Añadir partida</Button><div style={{marginTop:16}}><Button onClick={()=>setStep(3)}>Revisar propuesta</Button></div></div>}
    {step === 3 && <div className="sales-card"><h2>Revisión antes de guardar</h2><p><strong>{draft.titulo}</strong> · {draft.partidas.length} partidas · cliente: {active?.nombre}</p><p>Las notas y costes internos no forman parte de la versión que verá el cliente.</p><Button onClick={() => void submitEstimate()} loading={saving}>Guardar como borrador</Button></div>}
    <div style={{ marginTop:32 }}><h2>Propuestas recientes</h2>{estimates.length ? estimates.map(e=><div key={e.id} style={{padding:"12px 0",borderBottom:"1px solid var(--line)",display:"flex",justifyContent:"space-between"}}><span><strong>{e.numero}</strong> · {e.titulo} · v{e.versionActual}</span><span>{e.estado}</span></div>) : <p>Aún no hay propuestas.</p>}</div>
  </section>;
}
