import { useState } from "react";
import { Button, Input } from "@/shared/ui";
import type { UsersApi } from "@/features/users/api/users.api";
import { activationTokenFromLocation } from "../activation-token";
import { isValidAccountPassword } from "@reformapro/domain";

export function ActivateAccountPage({ api }: { api: UsersApi }) {
  const token = activationTokenFromLocation(window.location);
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [done, setDone] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); if (!token) return setError("El enlace de activación no es válido."); if (!isValidAccountPassword(password)) return setError("Usa al menos 12 caracteres, incluyendo letras y números."); if (password !== confirm) return setError("Las contraseñas no coinciden."); try { setSaving(true); await api.activateAccount(token, password); setDone(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo activar la cuenta."); } finally { setSaving(false); } };
  return <section className="login-page"><div className="login-card" style={{ maxWidth:440, margin:"0 auto", padding:40, background:"#fffaf4", border:"1px solid #d8c4ad", borderRadius:12 }}><img src="/brand/hogaria-wordmark.png" alt="Hogaria Reformas Integrales" style={{ display:"block", width:190, margin:"0 auto 28px" }} />{done ? <><h1>Cuenta activada</h1><p>Tu contraseña se ha creado correctamente. Ya puedes acceder a tu área privada.</p><Button onClick={() => { window.location.hash = "#/login"; }}>Iniciar sesión</Button></> : <form onSubmit={submit}><h1>Activa tu cuenta</h1><p style={{ color:"#71685e" }}>Crea una contraseña segura para acceder a tu área privada.</p>{error && <p role="alert" style={{ color:"#a43c32" }}>{error}</p>}<Input label="Nueva contraseña" type="password" required autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} /><p style={{ color:"#71685e", fontSize:12 }}>Mínimo 12 caracteres, con letras y números.</p><Input label="Repite la contraseña" type="password" required autoComplete="new-password" value={confirm} onChange={event => setConfirm(event.target.value)} /><Button type="submit" loading={saving}>Activar cuenta</Button></form>}</div></section>;
}
