import pg from "pg";
import { AuditEntry, Budget, BudgetLine, Project, User, UserRole } from "@reformapro/domain/entities";
import { Email, IVARate, Money, Percentage, DocumentHash } from "@reformapro/domain/value-objects";
import { Signature } from "@reformapro/domain/entities";
import { IAuditRepository, IBudgetRepository, IChallengeRepository, IProjectRepository, IUserRepository, Challenge } from "@reformapro/domain/repositories";
import { NotFoundError } from "@reformapro/domain/errors";
import type { PasswordHasher } from "./inMemoryRepositories.js";
import type { ProjectFile, IFileRepository } from "../../application/use-cases/file.use-cases.js";
import type { ISolicitudRepository } from "../../application/use-cases/solicitud.use-cases.js";

type Row = Record<string, any>;
const date = (value: string | Date) => new Date(value);
const projectPayload = (p: Project) => ({ ...p, progreso: p.progreso.value, presupuesto: p.presupuesto.amount, fechaInicio: p.fechaInicio.toISOString(), fechaFinPrevista: p.fechaFinPrevista.toISOString(), createdAt: p.createdAt.toISOString(), hitos: p.hitos.map(h => ({ ...h, fecha: h.fecha.toISOString() })) });
const restoreProject = (id: number, p: any): Project => ({ ...p, id, progreso: Percentage.of(p.progreso), presupuesto: Money.of(p.presupuesto), fechaInicio: date(p.fechaInicio), fechaFinPrevista: date(p.fechaFinPrevista), createdAt: date(p.createdAt), hitos: p.hitos.map((h: any) => ({ ...h, fecha: date(h.fecha) })) });
const budgetPayload = (b: Budget) => ({ ...b, ivaDefault: b.ivaDefault.value, fechaCreacion: b.fechaCreacion.toISOString(), fechaEnvio: b.fechaEnvio?.toISOString() ?? null, partidas: b.partidas.map(p => ({ ...p, precioUnit: p.precioUnit.amount, descuento: p.descuento.value, iva: p.iva?.value ?? null })), firma: b.firma ? { ...b.firma, firmanteEmail: b.firma.firmanteEmail.value, fechaFirma: b.firma.fechaFirma.toISOString(), hash: b.firma.hash.value, auditTrail: b.firma.auditTrail.map(a => ({ ...a, timestamp: a.timestamp.toISOString() })) } : null });
const restoreBudget = (id: number, b: any) => new Budget(id, b.proyectoId, b.clienteId, b.nombre, b.referencia, b.estado, IVARate.of(b.ivaDefault), b.validezDias, date(b.fechaCreacion), b.fechaEnvio ? date(b.fechaEnvio) : null, b.condicionesPago, b.garantia, b.notas, b.partidas.map((p: any) => new BudgetLine(p.id, p.categoria, p.descripcion, p.cantidad, p.unidad, Money.of(p.precioUnit), Percentage.of(p.descuento), p.iva == null ? null : IVARate.of(p.iva), p.ref, p.nota)), b.firma ? new Signature(b.firma.firmado, b.firma.firmante, Email.of(b.firma.firmanteEmail), date(b.firma.fechaFirma), b.firma.ip, DocumentHash.of(b.firma.hash), b.firma.token, b.firma.consentimiento, b.firma.auditTrail.map((a: any) => ({ ...a, timestamp: date(a.timestamp) }))) : null);

export class PostgresUserRepository implements IUserRepository {
  constructor(private readonly pool: pg.Pool, private readonly hasher: PasswordHasher) {}
  private map(r: Row): User { return { id: Number(r.id), email: Email.of(r.email), nombre: r.nombre, rol: r.rol as UserRole, activo: r.activo, createdAt: date(r.created_at), ...(r.profesion ? { profesion: r.profesion } : {}), ...(r.telefono ? { telefono: r.telefono } : {}) }; }
  async findById(id: number) { const r = await this.pool.query("SELECT * FROM users WHERE id=$1", [id]); return r.rows[0] ? this.map(r.rows[0]) : null; }
  async findByEmail(email: string) { const r = await this.pool.query("SELECT * FROM users WHERE lower(email)=lower($1)", [email]); return r.rows[0] ? this.map(r.rows[0]) : null; }
  async findAll() { return (await this.pool.query("SELECT * FROM users ORDER BY id")).rows.map(r => this.map(r)); }
  async findByRole(role: UserRole) { return (await this.pool.query("SELECT * FROM users WHERE rol=$1 ORDER BY id", [role])).rows.map(r => this.map(r)); }
  async save(user: User, passwordHash = "") { const r = await this.pool.query("INSERT INTO users(email,nombre,rol,profesion,telefono,activo,password_hash,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *", [user.email.value,user.nombre,user.rol,user.profesion ?? null,user.telefono ?? null,user.activo,passwordHash,user.createdAt]); return this.map(r.rows[0]); }
  async update(id: number, changes: Partial<Omit<User,"id"|"createdAt">>) { const current = await this.findById(id); if (!current) throw new NotFoundError("Usuario"); const next = { ...current, ...changes }; const r = await this.pool.query("UPDATE users SET nombre=$2, rol=$3, profesion=$4, telefono=$5, activo=$6 WHERE id=$1 RETURNING *", [id,next.nombre,next.rol,next.profesion ?? null,next.telefono ?? null,next.activo]); return this.map(r.rows[0]); }
  async delete(id: number) { await this.pool.query("DELETE FROM users WHERE id=$1", [id]); }
  async verifyPassword(email: string, plaintext: string) { const r = await this.pool.query("SELECT * FROM users WHERE lower(email)=lower($1)", [email]); if (!r.rows[0] || !(await this.hasher.verify(plaintext, r.rows[0].password_hash))) return null; return this.map(r.rows[0]); }
  async updatePassword(id: number, hash: string) { await this.pool.query("UPDATE users SET password_hash=$2 WHERE id=$1", [id, hash]); }
}

export class PostgresProjectRepository implements IProjectRepository {
  constructor(private readonly pool: pg.Pool) {} private map(r: Row) { return restoreProject(Number(r.id), r.payload); }
  async findById(id:number){const r=await this.pool.query("SELECT * FROM projects WHERE id=$1",[id]);return r.rows[0]?this.map(r.rows[0]):null} async findByClient(id:number){return(await this.pool.query("SELECT * FROM projects WHERE cliente_id=$1",[id])).rows.map(r=>this.map(r))} async findByProfesional(id:number){return(await this.pool.query("SELECT * FROM projects WHERE payload->'profesionalesAsignados' @> $1::jsonb",[JSON.stringify([{userId:id}])])).rows.map(r=>this.map(r))} async findAll(){return(await this.pool.query("SELECT * FROM projects ORDER BY id")).rows.map(r=>this.map(r))}
  async save(p:Project){const r=await this.pool.query("INSERT INTO projects(cliente_id,payload) VALUES($1,$2) RETURNING *",[p.clienteId,projectPayload(p)]);return this.map(r.rows[0])} async update(id:number,c:Partial<Omit<Project,"id"|"createdAt">>){const old=await this.findById(id);if(!old)throw new NotFoundError("Proyecto");const next={...old,...c};const r=await this.pool.query("UPDATE projects SET cliente_id=$2,payload=$3 WHERE id=$1 RETURNING *",[id,next.clienteId,projectPayload(next)]);return this.map(r.rows[0])} async delete(id:number){await this.pool.query("DELETE FROM projects WHERE id=$1",[id])}
}

export class PostgresBudgetRepository implements IBudgetRepository {
  constructor(private readonly pool: pg.Pool) {} private map(r:Row){return restoreBudget(Number(r.id),r.payload)} async findById(id:number){const r=await this.pool.query("SELECT * FROM budgets WHERE id=$1",[id]);return r.rows[0]?this.map(r.rows[0]):null} async findByProject(id:number){return(await this.pool.query("SELECT * FROM budgets WHERE proyecto_id=$1 ORDER BY id DESC",[id])).rows.map(r=>this.map(r))} async findByClient(id:number){return(await this.pool.query("SELECT * FROM budgets WHERE cliente_id=$1 ORDER BY id DESC",[id])).rows.map(r=>this.map(r))} async findAll(){return(await this.pool.query("SELECT * FROM budgets ORDER BY id DESC")).rows.map(r=>this.map(r))} async save(b:Budget){const r=await this.pool.query("INSERT INTO budgets(proyecto_id,cliente_id,payload) VALUES($1,$2,$3) RETURNING *",[b.proyectoId,b.clienteId,budgetPayload(b)]);return this.map(r.rows[0])} async update(id:number,c:Partial<Budget>){const old=await this.findById(id);if(!old)throw new NotFoundError("Presupuesto");const next=Object.assign(Object.create(Object.getPrototypeOf(old)),old,c) as Budget;const r=await this.pool.query("UPDATE budgets SET payload=$2 WHERE id=$1 RETURNING *",[id,budgetPayload(next)]);return this.map(r.rows[0])} async delete(id:number){await this.pool.query("DELETE FROM budgets WHERE id=$1",[id])}
}

export class PostgresChallengeRepository implements IChallengeRepository { constructor(private readonly pool:pg.Pool){} async get(id:number){const r=await this.pool.query("SELECT * FROM signature_challenges WHERE budget_id=$1 AND expires_at>NOW()",[id]);return r.rows[0]?{challenge:r.rows[0].challenge,timestamp:Number(r.rows[0].timestamp_ms),exp:date(r.rows[0].expires_at).getTime(),userId:Number(r.rows[0].user_id)}:null} async set(id:number,c:Challenge){await this.pool.query("INSERT INTO signature_challenges(budget_id,challenge,timestamp_ms,expires_at,user_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT (budget_id) DO UPDATE SET challenge=$2,timestamp_ms=$3,expires_at=$4,user_id=$5",[id,c.challenge,c.timestamp,new Date(c.exp),c.userId])} async delete(id:number){await this.pool.query("DELETE FROM signature_challenges WHERE budget_id=$1",[id])} }
export class PostgresAuditRepository implements IAuditRepository { constructor(private readonly pool:pg.Pool){} async append(e:AuditEntry){await this.pool.query("INSERT INTO audit_entries(id,payload,timestamp) VALUES($1,$2,$3)",[e.id,{...e,timestamp:e.timestamp.toISOString()},e.timestamp])} async findAll(){const r=await this.pool.query("SELECT payload FROM audit_entries ORDER BY timestamp DESC");const items=r.rows.map(x=>({...x.payload,timestamp:date(x.payload.timestamp)}));return{items,total:items.length,page:0,limit:50,pages:1}} }
export class PostgresSolicitudRepository implements ISolicitudRepository {
  constructor(private readonly pool: pg.Pool) {}
  private map(r: Row) { return { id: Number(r.id), nombre: r.nombre, email: r.email, telefono: r.telefono, tipo: r.tipo, descripcion: r.descripcion, estado: r.estado, ip: r.ip ?? "", fecha: date(r.fecha), motivo: r.motivo ?? null }; }
  async save(s: { nombre:string; email:string; telefono:string; tipo:string; descripcion:string; fecha:Date; estado:"pendiente"; ip:string }) { const r = await this.pool.query("INSERT INTO solicitudes(nombre,email,telefono,tipo,descripcion,estado,ip,fecha) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id", [s.nombre,s.email,s.telefono,s.tipo,s.descripcion,s.estado,s.ip,s.fecha]); return { id: Number(r.rows[0].id) }; }
  async findAll() { return (await this.pool.query("SELECT * FROM solicitudes ORDER BY fecha DESC")).rows.map(r => this.map(r)); }
  async findById(id: number) { const r = await this.pool.query("SELECT * FROM solicitudes WHERE id=$1", [id]); return r.rows[0] ? this.map(r.rows[0]) : null; }
  async update(id: number, changes: { estado: "contactado" | "rechazado"; motivo: string | null }) { const r = await this.pool.query("UPDATE solicitudes SET estado=$2,motivo=$3 WHERE id=$1 RETURNING *", [id, changes.estado, changes.motivo]); if (!r.rows[0]) throw new NotFoundError("Solicitud"); return this.map(r.rows[0]); }
}
export class PostgresFileRepository implements IFileRepository { constructor(private readonly pool: pg.Pool) {} async save(file: Omit<ProjectFile,"id">) { const r=await this.pool.query("INSERT INTO project_files(project_id,payload,uploaded_at) VALUES($1,$2,$3) RETURNING id",[file.projectId,{...file,uploadedAt:file.uploadedAt.toISOString()},file.uploadedAt]); return { ...file, id:Number(r.rows[0].id) }; } async findById(id:number) { const r=await this.pool.query("SELECT id,payload FROM project_files WHERE id=$1",[id]); return r.rows[0] ? { ...r.rows[0].payload, id:Number(r.rows[0].id), uploadedAt:date(r.rows[0].payload.uploadedAt) } as ProjectFile : null; } async findByProject(projectId:number) { const r=await this.pool.query("SELECT id,payload FROM project_files WHERE project_id=$1 ORDER BY id",[projectId]); return r.rows.map(row=>({ ...row.payload,id:Number(row.id),uploadedAt:date(row.payload.uploadedAt) } as ProjectFile)); } async delete(id:number) { await this.pool.query("DELETE FROM project_files WHERE id=$1",[id]); } }
