import { ForbiddenError, NotFoundError, ConflictError, ValidationError } from "@reformapro/domain/errors";
import type { IProjectRepository, IUserRepository } from "@reformapro/domain/repositories";

export type WorkSession = { id:number; projectId:number; professionalId:number; kind:"jornada"|"parte"; startedAt:Date; endedAt:Date|null; breakMinutes:number; units:number|null; unitLabel:string|null; costRate:number; rateUnit:"hora"|"jornada"|"unidad"; notes:string; status:"abierto"|"enviado"|"aprobado"|"rechazado"; approvedBy:number|null; approvedAt:Date|null; createdAt:Date };
export interface IWorkSessionRepository { save(input:Omit<WorkSession,"id"|"createdAt">):Promise<WorkSession>; findById(id:number):Promise<WorkSession|null>; find(projectId?:number, professionalId?:number):Promise<WorkSession[]>; update(id:number, changes:Partial<WorkSession>):Promise<WorkSession>; }

export class WorkTrackingUseCases {
  constructor(private readonly users:IUserRepository, private readonly projects:IProjectRepository, private readonly sessions:IWorkSessionRepository) {}
  async start(actorId:number, projectId:number) { const user=await this.users.findById(actorId); const project=await this.projects.findById(projectId); if(!user||user.rol!=="profesional"||!user.activo||!project||!project.profesionalesAsignados.some(a=>a.userId===actorId)) throw new ForbiddenError(); if((await this.sessions.find(undefined,actorId)).some(s=>s.status==="abierto")) throw new ConflictError("Ya tienes una jornada abierta"); return this.sessions.save({projectId,professionalId:actorId,kind:"jornada",startedAt:new Date(),endedAt:null,breakMinutes:0,units:null,unitLabel:null,costRate:0,rateUnit:"hora",notes:"",status:"abierto",approvedBy:null,approvedAt:null}); }
  async finish(actorId:number,id:number, breakMinutes=0, notes="") { const s=await this.sessions.findById(id); if(!s||s.professionalId!==actorId||s.status!=="abierto") throw new NotFoundError("Jornada abierta"); if(!Number.isInteger(breakMinutes)||breakMinutes<0) throw new ValidationError("Pausa inválida","breakMinutes"); return this.sessions.update(id,{endedAt:new Date(),breakMinutes,notes:notes.trim().slice(0,1000),status:"enviado"}); }
  async submitPart(actorId:number, input:{projectId:number; startedAt:string; endedAt:string; units?:number; unitLabel?:string; notes?:string}) { const user=await this.users.findById(actorId); const project=await this.projects.findById(input.projectId); if(!user||user.rol!=="profesional"||!project||!project.profesionalesAsignados.some(a=>a.userId===actorId)) throw new ForbiddenError(); const start=new Date(input.startedAt), end=new Date(input.endedAt); if(Number.isNaN(start.getTime())||end<=start) throw new ValidationError("Horario inválido"); return this.sessions.save({projectId:input.projectId,professionalId:actorId,kind:"parte",startedAt:start,endedAt:end,breakMinutes:0,units:input.units??null,unitLabel:input.unitLabel?.trim()||null,costRate:0,rateUnit:"hora",notes:input.notes?.trim().slice(0,1000)||"",status:"enviado",approvedBy:null,approvedAt:null}); }
  async list(actorId:number, projectId?:number) { const user=await this.users.findById(actorId); if(!user) throw new ForbiddenError(); if(user.rol==="admin") return this.sessions.find(projectId); return this.sessions.find(projectId,user.id); }
  async approve(actorId:number,id:number, approve:boolean) { const admin=await this.users.findById(actorId); if(!admin||admin.rol!=="admin") throw new ForbiddenError(); const s=await this.sessions.findById(id); if(!s||s.status!=="enviado") throw new NotFoundError("Parte pendiente"); return this.sessions.update(id,{status:approve?"aprobado":"rechazado",approvedBy:actorId,approvedAt:new Date()}); }
}
